name: second_late_fusion_low_res
root_dir: "opv2v_data_dumping/train"
validate_dir: "opv2v_data_dumping/validate"

yaml_parser: "load_second_params"
train_params:
  batch_size: &batch_size 2
  epoches: 40
  eval_freq: 1
  save_freq: 1

fusion:
  core_method: 'LateFusionDataset' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported
  args: []

# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.1, 0.1, 0.1]
    max_points_per_voxel: 5
    max_voxel_train: 16000
    max_voxel_test: 40000
  # lidar range for each individual cav.
  cav_lidar_range: &cav_lidar [-70.4, -40, -3, 70.4, 40, 1]

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: [0, 90]
    feature_stride: 8
    num: &achor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.20
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15

# model related
model:
  core_method: second
  args:
    batch_size: *batch_size
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    mean_vfe:
      feature_points: 4

    backbone_3d: []

    height_compression:
      feature_num: 256

    base_bev_backbone:
      layer_nums: [5, 5]
      layer_strides: [1, 2]
      num_filters: [128, 256]
      upsample_strides: [1, 2]
      num_upsample_filter: [256, 256]

    anchor_num: *achor_num

loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg: 2.0

optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [15, 30]

